modelName: "fractal"
nContrib: 300
modelDType: "default"
fitParameterLimits:
  volfraction: 'auto'
  radius: 'auto' # automatic determination of radius limits based on the data limits. This is replaced in McHat by actual limits
  fractal_dim: 
    - 1
    - 3
  cor_length: 'auto'
staticParameters:
  sld_block: 33.4 # units of 1e-6 A^-2
  sld_solvent: 0
maxIter: 100000
convCrit: 1
nRep: 10
nCores: 5
